django_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

app_name = 'django_app'


urlpatterns = [
	url(r'^django_app/', include('project_v1.urls', namespace='project_v1')),
    url(r'^admin/', include(admin.site.urls)),
]

project_v1/urls.py
from django.conf.urls import url

from . import views

app_name = 'project_v1'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<question_id>[0-9]+)/result/$', views.result, name='result'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	]

project_v1/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('Publishing Date')
	def __str__(self):
		return self.question_text

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)	
	def __str__(self):
		return self.choice_text

project_v1/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from .models import Choice, Question
from django.conf.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse

def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	data = {'latest_question_list': latest_question_list,}
	return render(request,'project_v1/index.html', data)

def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	data = {'question' : question}
	return render(request, "project_v1/detail.html", data)

def result(request, question_id):
	return render(request, "you are looking at the result of question %s." %question_id)

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except(KeyError, Choice.DoesNotExist):
		return render(request, 'project_v1/detail.html',{
			'question': question,
			'error_message': "You didn't select a choice",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
	return HttpResponseRedirect(reverse('project_v1:results', args=(question.id,)))

project_v1/templates/app/index.html
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{{ question.id }}/">{{ question.question_text }}</a></li>
	{% endfor %}
{% else %}
	<p>No Polls are available..</p>
{% endif %}

project_v1/templates/project_v1/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'project_v1:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="vote">
</form>
<ul>
	{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }}</li>
	{% endfor %}
</ul>

project_v1/templates/project_v1/index.html
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'project_v1:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
{% else %}
	<p>No Polls are available..</p>
{% endif %}